### ISSUE TITLE
Extra spaces yml file fails to get secrets

### ISSUE THREAD

**Issue by MartinSeman** [cyberark/conjur-azure-devops-extension#7]
## Summary
Incorrect line in yml file log no error, Task end with result success, but password is not retrieved

## Steps to Reproduce
1. edit *.yml file
2. add moore spaces between variable and "!var" - e.g. "gammaServicesUserPwd:        !var epv/CAR_TA_LOBGe...."
3. run task
4. See log

## Expected Results
Duplicate spaces are ignored and password is retrieved or error is logged and task failed

## Actual Results (including error logs, if applicable)
Task end with result success, but password is not retrieved and no error in log

**Comment by rpothier** [comment]
Thanks for submitting this issue @MartinSeman 

It looks like there might be places that expect a single space and that gets the behaviour that you are seeing,
like in [103](https://github.com/cyberark/conjur-azure-devops-extension/blob/e51a4c680629e25f40a66caf2b2740ef2ef0ba73/conjurTask/index.ts#L103)

**Comment by MartinSeman** [comment]
OK, i expect error in log `Failed to retrieve secret name and path from '${line}' - line 105. But log is empty and task end with result "Success" ;(

**Comment by rpothier** [comment]
What about line #129? That looks like it could skip without an error. Are you able to add any debug?

**Comment by infamousjoeg** [comment]
> OK, i expect error in log `Failed to retrieve secret name and path from '${line}' - line 105. But log is empty and task end with result "Success" ;(

This issue was fixed as part of PR #14 and can be experienced in the published extension at https://marketplace.visualstudio.com/items?itemName=InfamousJoeG.cyberark-conjur-secrets.
